### ISSUE TITLE
Во время коммита типы проверяются с ошибкой

### ISSUE THREAD

**Issue by zhitkovkostya** [viberoom-radio/viberoom-client#58]
Есть 2 проблемы:

1. Типы проверяются в том числе и для js/jsx файлов, хотя должны только для ts/tsx

```
"src/**/*.{js,jsx,ts,tsx}": [
    "npm run format:fix",
    "npm run lint",
    "npm run types"
],
```

2. Проверка типов некорректно отрабатывает, если сделать ошибку типов и попытаться закоммитить изменения. Насколько вижу, эту проблему решает библиотека [tsc-files](https://github.com/gustavopch/tsc-files), можно проверить ее.

**Comment by Lacsw** [comment]
Теперь ошибки при неверном типе во время коммита смотрятся читабельно :) ![Снимок экрана 2023-07-12 в 13 51 31](https://github.com/viberoom-radio/viberoom-client/assets/12248879/3404218e-e145-4ff6-b46d-7133d94c7130)
